In [5]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [6]:
import pandas as pd
import numpy as np

In [7]:
r1 = np.array([2, 3, 7])
r2 = np.array([5, 8, 1])
X1 = np.array([r1, r2])

X2 = np.matrix([[2, 3, 7], [5, 8, 1]])
X1, X2

(array([[2, 3, 7],
        [5, 8, 1]]),
 matrix([[2, 3, 7],
         [5, 8, 1]]))

In [13]:
# X1.shape, X2.shape
N, T = X1.shape
ones = np.ones(T)
onesT = np.ones((1, T))

m = (1 / T) * X2 @ ones
N, T


(2, 3)

In [12]:
C = np.eye(T) - np.ones((T, T)) / T
cov = (1/ T) * X1 @ C @ X1.T # biased
# cov = (1/ (T - 1)) * X1 @ C @ X1.T # unbiased
cov

# numpy equivalent
np.cov(X1)
np.cov(X1, bias = True), cov

(array([[ 4.66666667, -5.        ],
        [-5.        ,  8.22222222]]),
 array([[ 4.66666667, -5.        ],
        [-5.        ,  8.22222222]]))

In [91]:
cov = (1 / T) * (X1 - m.T @ onesT) @ (X1 - m.T @ onesT).T
cov


matrix([[ 4.66666667, -5.        ],
        [-5.        ,  8.22222222]])

### Single-index covariance matrix estimator

In [100]:
T = 10
N = 4

market = 0.15 * np.random.randn(T)
market

# Simulate stock returns: each stock has its own beta plus idiosyncratic noise
true_betas = np.array([1.0, 0.8, 1.2, 0.5])
true_alphas = np.array([0.001, -0.0005, 0.0007, 0.0])
res_sd = np.array([0.10, 0.08, 0.12, 0.09])



# X = true_alphas[:, None] + true_betas[:, None] * market + res_sd[:, None] * np.random.randn(N, T)
X = true_alphas[:, None] + true_betas[:, None] * market + res_sd[:, None] * np.random.randn(N, T)
X

mean_market = market.mean()
mean_assets = X.mean(axis=1)

In [101]:
X

array([[-0.25867971, -0.1227397 ,  0.31068824,  0.23343724, -0.14045157,
         0.04843621,  0.25704411,  0.03721777,  0.00187168, -0.07490585],
       [-0.11016023,  0.06730497,  0.11465434,  0.16398198, -0.01759751,
        -0.00740461,  0.17287982,  0.07427932, -0.13272981,  0.08698662],
       [-0.37198163, -0.0124372 ,  0.27439286,  0.18899402, -0.1594805 ,
        -0.15665467,  0.25302041,  0.12726531, -0.26113185,  0.1076859 ],
       [-0.09962955,  0.25087229,  0.13455012,  0.03727134, -0.11305054,
        -0.06256214,  0.15284172, -0.03303238, -0.03332736,  0.02796565]])

In [102]:
mean_assets

array([ 0.02919184,  0.04121949, -0.00103274,  0.02618992])

In [104]:
A = np.matrix([[1, 2], [3, 4]])
np.linalg.norm(A, 'fro')

np.float64(5.477225575051661)